config/routes.rb
Myapp::Application.routes.draw do

  resources :elections

  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'

  authenticated :user do
    root to: 'home#index'
  end
  root to: "home#index"

  devise_for :users
  resources :users, only: [:show, :index]
  resources :areas

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do. If you pass :manage it will apply to every action.
    # Other common actions here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects. For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/area.rb
class Area
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :type, type: String
  belongs_to :parent, class_name: "Area", inverse_of: :divisions
  has_many :divisions, class_name: "Area", inverse_of: :parent
  has_many :elections
  attr_accessible :name, :type, :parent_id
  validates :name, presence: true,
                   uniqueness: { case_sensitive: false, scope: :parent },
                   length: 2..30
  validates :type, presence: true

  validate do
    p = [ self ]
    until p.last.parent.nil?
      if p.include?(p.last.parent) || p.length >= 20
        errors.add :parent, errors.generate_message(:parent, :ciclic_reference)
        break
      else
        p << p.last.parent
      end
    end
  end
end

app/models/election.rb
class Election
  include Mongoid::Document
  include Mongoid::Timestamps
  field :election_start, type: Date
  field :election_end, type: Date
  field :post, type: String
  belongs_to :area
  attr_accessible :_id, :area_id, :election_start, :election_end, :post
  validates :area, presence: true
  validates :post, presence: true, length: 2..30
  validates :election_end, presence: true

  validate do
    if election_end? && election_start? && election_start > election_end
      errors.add :election_start,
                 errors.generate_message(:election_start, :inverted_range)
    end
  end
end

app/models/role.rb
class Role
  include Mongoid::Document

  has_and_belongs_to_many :users
  belongs_to :resource, polymorphic: true

  field :name, type: String
  index({ name: 1}, { unique: true })
  index({ name: 1, resource_type: 1, resource_id: 1 }, { unique: true })
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  extend Rolify
  rolify

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  validates_presence_of :email
  validates_presence_of :encrypted_password

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  field :confirmation_token,   type: String
  field :confirmed_at,         type: Time
  field :confirmation_sent_at, type: Time
  field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # Only if lock strategy is :failed_attempts
  # field :failed_attempts, type: Integer, default: 0
  # Only if unlock strategy is :email or :both
  # field :unlock_token,    type: String
  # field :locked_at,       type: Time

  ## Token authenticatable
  # field :authentication_token, type: String
  # run 'rake db:mongoid:create_indexes' to create indexes
  index({ email: 1 }, { unique: true })
  field :name
  validates_presence_of :name
  attr_accessible :name, :email, :password, :password_confirmation,
                  :remember_me, :confirmed_at, :created_at, :updated_at
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  inherit_resources
  before_filter :authenticate_user!, except: [:index, :show]
  has_scope :page, default: 1
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  inherit_resources
  before_filter :authenticate_user!, except: [:index, :show]
  has_scope :page, default: 1
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  inherit_resources
  defaults resource_class: User, collection_name: :users, instance_name: :user
  actions :index
  has_scope :page, default: 1
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  inherit_resources
  before_filter :authenticate_user!
  actions :index, :show
  has_scope :page, default: 1

  def index
    authorize! :index, @user, message: 'Not authorized as an administrator.'
    index!
  end

end

app/views/areas/_form.html.haml
= simple_form_for(area) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :type
    = f.input :parent_id, collection: Area.all.where(:_id.ne => area._id), value_method: :_id, label_method: :name

  .form-actions
    = f.button :submit

app/views/areas/edit.html.haml
%h1 Editing area

= render 'form', area: @area

= link_to 'Show', @area
\|
= link_to 'Back', areas_path

app/views/areas/index.html.haml
%h1 Listing areas

%table
  %tr
    %th Name
    %th Type
    %th Parent
    %th
    %th
    %th

  - @areas.each do |area|
    %tr
      %td= link_to area.name, area
      %td= area.type
      %td= link_to area.parent.name, area.parent unless area.parent.nil?
      %td= link_to 'Edit', edit_area_path(area)
      %td= link_to 'Destroy', area, data: { confirm: 'Are you sure?' }, method: :delete

= paginate @areas

%br

= link_to 'New Area', new_area_path

app/views/areas/new.html.haml
%h1 New area

= render 'form', area: @area

= link_to 'Back', areas_path

app/views/areas/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @area.name
%p
  %b Type:
  = @area.type
%p
  %b Parent:
  = "#{@area.parent.name} (#{@area.parent.type})" if @area.parent

= link_to 'Edit', edit_area_path(@area)
\|
= link_to 'Back', areas_path

app/views/elections/_form.html.haml
= simple_form_for(election) do |f|
  = f.error_notification

  .form-inputs
    = f.input :area, collection: Area.all
    = f.input :election_start
    = f.input :election_end
    = f.input :post

  .form-actions
    = f.button :submit

app/views/elections/edit.html.haml
%h1 Editing election

= render 'form', election: @election

= link_to 'Show', @election
\|
= link_to 'Back', elections_path

app/views/elections/index.html.haml
%h1 Listing elections

%table
  %tr
    %th Area
    %th Election start
    %th Election end
    %th Post
    %th
    %th
    %th

  - @elections.each do |election|
    %tr
      %td= link_to election.area.name, election.area
      %td= election.election_start
      %td= election.election_end
      %td= election.post
      %td= link_to 'Show', election
      %td= link_to 'Edit', edit_election_path(election)
      %td= link_to 'Destroy', election, confirm: 'Are you sure?', method: :delete

= paginate @elections

%br

= link_to 'New Election', new_election_path

app/views/elections/new.html.haml
%h1 New election

= render 'form', election: @election

= link_to 'Back', elections_path

app/views/elections/show.html.haml
%p#notice= notice

%p
  %b Area:
  = "#{@election.area.name} (#{@election.area.type})" if @election.area
%p
  %b Election start:
  = @election.election_start
%p
  %b Election end:
  = @election.election_end
%p
  %b Post:
  = @election.post

= link_to 'Edit', edit_election_path(@election)
\|
= link_to 'Back', elections_path

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p User: #{link_to user.name, user}

= paginate @users

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{class: "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Myapp", root_path, class: 'brand'
%ul.nav
  %li
    = link_to('Areas', areas_path)
  %li
    = link_to('Elections', elections_path)
  - if user_signed_in?
    %li
      = link_to('Logout', destroy_user_session_path, method: 'delete')
  - else
    %li
      = link_to('Login', new_user_session_path)
  - if user_signed_in?
    %li
      = link_to('Edit account', edit_user_registration_path)
    - if current_user.has_role? :admin
      %li
        = link_to('Admin', users_path)
  - else
    %li
      = link_to('Sign up', new_user_registration_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", content: "IE=edge,chrome=1"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Myapp"
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{role: "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/users/index.html.haml
%h2 Users
- @users.each do |user|
  %br/
  #{link_to user.email, user} signed up #{user.created_at.to_date}

= paginate @users

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}